### ISSUE TITLE
Can not use for mount directory

### ISSUE THREAD

**Issue by oracleloyall** [davechri/snapshot-fs#1]
->logs output like follow:
tid=3956754176 ##error## Getattr:208 /home/test/snapshot/data: lstat failed errno=2 /*

In mount directory can not show any remoting storage files!

**Comment by davechri** [comment]
What Linix distro are you using?  The original development was done on Fedora and Redhat.

I'm seeing what may be the same issue on Mint (Ubuntu).

**Comment by davechri** [comment]
Please let me know if you are still having an issue after pulling my latest commit.
